/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module
public import VCVio.OracleComp.Constructions.SampleableType
public import VCVio.OracleComp.EvalDist
public import VCVio.OracleComp.ProbComp

/-!
# Pseudorandom Generators (PRGs)

This file defines pseudorandom generators and their security game.

A PRG stretches a short random seed into a longer pseudorandom output.
Security means no efficient adversary can distinguish `gen(s)` (for a random seed `s`)
from a truly random output `r`.

## Main Definitions

- `PRGScheme S R` — a PRG with seed space `S` and output space `R`.
- `PRGAdversary R` — a distinguisher receiving a single value in `R`.
- `prgRealExp` — the real experiment (adversary sees `gen(s)` for random `s`).
- `prgIdealExp` — the ideal experiment (adversary sees random `r`).
- `prgAdvantage` — distinguishing advantage.
-/

@[expose] public section

open OracleComp OracleSpec ENNReal

/-- A pseudorandom generator with seed space `S` and output space `R`.
The generator is a deterministic function; security comes from the
seed being sampled uniformly. -/
structure PRGScheme (S R : Type) where
  gen : S → R

namespace PRGScheme

variable {S R : Type}

/-- A PRG adversary receives a single value and guesses whether it was
generated by the PRG or sampled uniformly. -/
abbrev PRGAdversary (R : Type) := R → ProbComp Bool

/-- Real PRG experiment: sample a random seed and let the adversary
see the PRG output. -/
def prgRealExp [SampleableType S] (prg : PRGScheme S R) (adversary : PRGAdversary R) :
    ProbComp Bool := do
  let s ← $ᵗ S
  adversary (prg.gen s)

/-- Ideal PRG experiment: let the adversary see a uniformly random value. -/
def prgIdealExp [SampleableType R] (adversary : PRGAdversary R) : ProbComp Bool := do
  let r ← $ᵗ R
  adversary r

/-- PRG advantage: how well the adversary distinguishes PRG output from random. -/
noncomputable def prgAdvantage [SampleableType S] [SampleableType R]
    (prg : PRGScheme S R) (adversary : PRGAdversary R) : ℝ :=
  |(Pr[= true | prg.prgRealExp adversary]).toReal -
    (Pr[= true | prgIdealExp adversary]).toReal|

end PRGScheme
